server:
  port: 9002
spring:
  application:
    name: ihrm-system #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.70.181.89:3306/ihrm?useUnicode=true&characterEncoding=utf8
    username: ihrm
    password: 5178019qq
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true

jwt:
  config:
    key: saas-ihrm
    ttl: 3600000
